sylius_twig_hooks:
    hooks:
        'sylius_shop.product.show.content':
            social_proof_widgets:
                template: '@SyliusSocialProofPlugin/shop/product_widgets.html.twig'
                priority: 50
